// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function pickEnv(...candidates: (string | undefined)[]): string | undefined {
  for (const c of candidates) {
    if (c != null && String(c).trim() !== "") return String(c).trim();
  }
  return undefined;
}

function createSupabaseClient() {
  // Browser: Vite inlines import.meta.env.VITE_* at build time.
  // Node (Vercel Functions / SSR): prefer process.env — vars are often only injected at
  // runtime on the server, while import.meta may be empty if they were not present at build.
  const proc = typeof process !== "undefined" ? process.env : undefined;
  const SUPABASE_URL = pickEnv(
    proc?.SUPABASE_URL,
    proc?.VITE_SUPABASE_URL,
    import.meta.env.VITE_SUPABASE_URL,
  );
  const SUPABASE_PUBLISHABLE_KEY = pickEnv(
    proc?.SUPABASE_PUBLISHABLE_KEY,
    proc?.VITE_SUPABASE_PUBLISHABLE_KEY,
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL or VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. In Vercel, add them for Production and redeploy (Build + Runtime).`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

